# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "./mo-data"

[log]
level = "info"

[malloc]
check-fraction = 65536
enable-metrics = true
[observability]
#enableMetricToProm = true
enable-metric-to-prom = true
enable-stmt-merge = true
